### PR TITLE
Add notes about prometheus recording rules

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Add notes about Prometheus recording rules.

issue: https://github.com/giantswarm/giantswarm/issues/19855

### CODE REVIEW

**Comment by mcbenjemaa** [comment]
This PR meant to be merged after #21

**Review by whites11 — APPROVED** [review]

**Comment by mcbenjemaa** [comment]
@whites11  Maybe  check this [comment](https://github.com/giantswarm/dashboards/pull/154#issuecomment-1137653742)

**Comment by mcbenjemaa** [comment]
Those dashboards are created by k8s community, they are very useful. the community uses a tech called mixin (which is basically a way of bundling rules, alerts, and dashboards together, with some customization that can be applied)

This is the [upstream](https://github.com/kubernetes-monitoring/kubernetes-mixin)

You can access the dashboards by filtering using tag `kubernetes-mixin`

**Comment by mcbenjemaa** [comment]
@QuentinBisson Can you review this PR

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
